# Generated by Django 5.0.2 on 2024-03-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('ci', models.IntegerField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=50)),
                ('contrasena', models.TextField()),
            ],
        ),
    ]
