# Generated by Django 5.0.2 on 2024-03-23 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_or_register', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Usuario',
        ),
    ]
