# Generated by Django 5.0.2 on 2024-03-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_or_register', '0002_rename_user_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ci',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
