# Generated by Django 5.0.2 on 2024-03-23 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_or_register', '0003_alter_usuario_ci'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='login_or_register.usuario')),
                ('puesto', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(max_length=100)),
            ],
            bases=('login_or_register.usuario', models.Model),
        ),
    ]
