# Generated by Django 5.0.2 on 2024-03-23 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_or_register', '0004_empleado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
