# Generated by Django 5.0.2 on 2024-03-23 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_or_register', '0006_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuestoTrabajo',
            fields=[
                ('id_puesto', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre_puesto', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ci',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login_or_register.puestotrabajo'),
        ),
    ]
