# Generated by Django 5.0.2 on 2024-03-23 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_or_register', '0007_puestotrabajo_alter_usuario_ci_alter_usuario_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_or_register.usuario')),
            ],
        ),
    ]
