# Generated by Django 5.0.2 on 2024-03-18 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Opinions',
            new_name='Opinion',
        ),
    ]
