# Generated by Django 5.0.2 on 2024-03-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_opinions_opinion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_comentario', models.IntegerField()),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('correo_usuario', models.CharField(max_length=100)),
                ('comentario_usuario', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Opinion',
        ),
    ]
