# Generated by Django 5.0.2 on 2024-03-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_comentario_delete_opinion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='id',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='id_comentario',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
