# Generated by Django 5.0.2 on 2024-03-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('disponibilidad', models.IntegerField()),
                ('categoria', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id_menu', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_menu', models.CharField(max_length=100)),
                ('lista_productos', models.ManyToManyField(to='menu.producto')),
            ],
        ),
    ]
